[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "219a4d5c3285a4be751ba0ea54dd714f106b8253"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "05d7f6a7117ccff24d9c5c94de63ff1cdf6511eb863f46906679c43f2f9a14a8"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.6+0/TempestRemap.v2.1.6.aarch64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0972720773f43a9f9ec9340282f152018327ba7f"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "734fed747103e3590b841730a272151c46f4bc692fea0c7a42bb2a34e1cb57a6"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.6+0/TempestRemap.v2.1.6.aarch64-linux-gnu-cxx11.tar.gz"
[[TempestRemap]]
arch = "x86_64"
git-tree-sha1 = "3b1ec7364bf12a41e906e458097807898466cc2d"
os = "macos"

    [[TempestRemap.download]]
    sha256 = "8743354842aac2a4d4ac02453abd504283e53bc1bea2c17b856bff244f881b20"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.6+0/TempestRemap.v2.1.6.x86_64-apple-darwin.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42918cd58df7e4eea1450cd39b066b920215160c"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "859bc5f45ed9948eccb16fc64da2072956cc20f36640784bb3ad657594b24785"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.6+0/TempestRemap.v2.1.6.x86_64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e5ad064e8289a3233f5d55752df3ffd8438eef4"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "5b599407a715d4bd5272898114cf5f19dffd374fd6bda7f447fa5261e7f4e3ec"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.6+0/TempestRemap.v2.1.6.x86_64-linux-gnu-cxx11.tar.gz"
