[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c903e729328242e184211da22e9b5d398f9f8cf7"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "c6545767d1c95d712b3fcfb1d24b73046a5114869c2231db6df4c4bb58f36f29"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+0/TempestRemap.v2.1.3.aarch64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03d6f8f5356c15181b92d3bbef26f888a73062ee"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "4ae3e6298f9d6d183a29e4532d5a97f383fd1e385e839b46199ca15d96e8dd9b"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+0/TempestRemap.v2.1.3.aarch64-linux-gnu-cxx11.tar.gz"
[[TempestRemap]]
arch = "x86_64"
git-tree-sha1 = "f67b72a3c68a46ae31ad6b6d84a13b4ecfa47c3e"
os = "macos"

    [[TempestRemap.download]]
    sha256 = "5a8d39f32c6cf0a8f7bac7e31bdd874d0a96e4411e0b10bce3a927d0e4ff8ea2"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+0/TempestRemap.v2.1.3.x86_64-apple-darwin.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52b47a085d272227eda8ed472bab3924df81d0f1"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "baaa7b0d685655362965189543c1f5af033d9a3ed9f90e6bc9f9b0eeb24fa953"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+0/TempestRemap.v2.1.3.x86_64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b19e339164f3817f48e25611497867590cf53d1b"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "443d535f23217ddaa0356161261218b9c6b2c266861d32c858fd29bb9844f082"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+0/TempestRemap.v2.1.3.x86_64-linux-gnu-cxx11.tar.gz"
