[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c770b4768742255e568d03be8537f383e8b3bb0"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "d2a501836d13f1984ee03f54328f0cdf26beae1e852b914b71db17d7269a9319"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+3/TempestRemap.v2.1.3.aarch64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a734a1d3c5f2e1fcbf359a2cfecbecbaedd90039"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "1a42d56d897f6ffae97f16b2d36c05e15de61f2b98b093a9502e7736d69b2f94"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+3/TempestRemap.v2.1.3.aarch64-linux-gnu-cxx11.tar.gz"
[[TempestRemap]]
arch = "x86_64"
git-tree-sha1 = "446263f557087773355c4350ae95b490777ae482"
os = "macos"

    [[TempestRemap.download]]
    sha256 = "a0c6930c0c8824332f43d53eb3c4244409ce71605e69e38656df9428d63c90d1"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+3/TempestRemap.v2.1.3.x86_64-apple-darwin.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a48841931ddf0fe9a065f8751d1957eeccb5804b"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "ddd59cf411250a86be072a94001dc4498da40813538a9a7b6fb06ddb69476119"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+3/TempestRemap.v2.1.3.x86_64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1736d8473cda77b39322f0fdf712946b33e70381"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "4fe5e9b419732e8eac500086acfac8438c0595126359a076356eb0b37c15d6b7"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+3/TempestRemap.v2.1.3.x86_64-linux-gnu-cxx11.tar.gz"
