[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63aba9bb488f5ebafe5c4d26475436e8d6537cb8"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "95937170fcc36c7cf24c874dc05bccc4cd37079bec854b5f4c7b34a3b9fbc71d"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+2/TempestRemap.v2.1.3.aarch64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3df014b52c69d4a8f06f4a48010700367a08e6fd"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "2c49d678e67b1d4c06514a1079ab13024437f6d7273f361ea0a21305b6ef5002"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+2/TempestRemap.v2.1.3.aarch64-linux-gnu-cxx11.tar.gz"
[[TempestRemap]]
arch = "x86_64"
git-tree-sha1 = "78565ae29c612203abb1c795c962d729e22e70ff"
os = "macos"

    [[TempestRemap.download]]
    sha256 = "c3e157e1058fe1f8f91f9a438098b63a761bf0a5fe0a67632fa4e4694676f2ac"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+2/TempestRemap.v2.1.3.x86_64-apple-darwin.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "805ba29dd1b1a214ea95fcb7d5a4db281b5c0fa4"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "3574af5199f1d31587575e462c71a5b5a38db66cbcd741723a8763b440ae957d"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+2/TempestRemap.v2.1.3.x86_64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db8bb055d059e1c04bade7bd86a3010466d5ad4a"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "e84caf810e21dc003fcc5d7b7cd977a807b34ce554b7207728d6d376ac753772"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+2/TempestRemap.v2.1.3.x86_64-linux-gnu-cxx11.tar.gz"
