[[TempestRemap]]
arch = "aarch64"
git-tree-sha1 = "c538e47a626f5f4639e05a63c9644c84cda7cb9b"
os = "macos"

    [[TempestRemap.download]]
    sha256 = "a47a11e9c902fd9f653b6c7b7b69f78a8255a23270c894497652c878284f9b1d"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.aarch64-apple-darwin.tar.gz"
[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47c7e8b5bea1bc83f075621b797e9fb2ad163a33"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "4027421f5007b404ae3cb684410197f9704b36575e44a9d3f19d803bff916c8c"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f9585f97441a4521f082f60434a9d7687552bad"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "4db19a95c1dacc0b6fab120227220fe22d997ef532d07348cf5ac4452afea4ec"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[TempestRemap]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2be86bb0415052a76b1492a4f82d69903052b2c7"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "4dbc3ad3ffb88b540a0d222909bd43adf2e021eb0500037839bd8d8788fdfe05"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[TempestRemap]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51c4c9c8325d3b9abe414d08d37c74048f9f0d93"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "86bc8e7e68f3a3dc013c5d01b9619679bd169d8a8bdf7e3cba4e7ca1f04917bf"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[TempestRemap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f08262017fc4a97a4e0a6ab4e1a0afdd36f60783"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "3c4a444509d15afd094e682fc0c4211c9b569eb890b4485321df3959fff3e60d"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[TempestRemap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90d4dbec7e0f0645475d58bb64322fd8f90186a9"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "3f941fff47645b98f1cc40b665db20c3c2ec9cd81b52bb26fe62eb138669eb36"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[TempestRemap]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cb5f1ae50887d086219f76e146ad317bf336ac4"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "136664b2f0caa596e238b08121864280d9ded8b2dc5090617c7f5c976c4089bf"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.i686-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7499266ab64a1b0cef216404336d9c5ad75b80a1"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "52de14e7edc3c9b4921377826f0714edbfb0dcf79d055926018a7450dc9e5a32"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.i686-linux-gnu-cxx11.tar.gz"
[[TempestRemap]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c01ee7a8f93b59ed31cdc57521d8d4c517b3678"
os = "windows"

    [[TempestRemap.download]]
    sha256 = "bdabbcad7f957864a0c04072118489c77ba37994a472faa012456a46bfe0d337"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[TempestRemap]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ae5305aeab1b12a3b0d32510075892b57d88e19"
os = "windows"

    [[TempestRemap.download]]
    sha256 = "e84524eb97b3a9de85e462e27b6452c9071995945af74b75a5c7182b07624e81"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[TempestRemap]]
arch = "x86_64"
git-tree-sha1 = "4a8876ae1787a981468213388c1cb83b68e28871"
os = "macos"

    [[TempestRemap.download]]
    sha256 = "0971a9c80e99cd30cc7391deb7ac553adee2e8be4efec490a47ef13ea251b170"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.x86_64-apple-darwin.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be8b04b9db753780375d9fe3d90c746d1b0ebc38"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "564d6dc24e32f97ae14230e524a199e84907e36684acd6b145adaaa1bc83d8f7"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2211caeb3d70d6476760f76a775b9295c6732035"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "dff0125b66e16585b59813199fb80f6e9eb47e49cfa2f3bb61c3626ca29ecf00"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[TempestRemap]]
arch = "x86_64"
git-tree-sha1 = "334cce9e5144a9cd39e92ee647efdb876826e2f0"
os = "freebsd"

    [[TempestRemap.download]]
    sha256 = "8e463ff249c8a3bfa89a5966d76d8b5ebde445a0ea1bfa2a749d6b7083f9321c"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.x86_64-unknown-freebsd.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa01bc8bca6a814b61903b4ee3c19ef14f2793cc"
os = "windows"

    [[TempestRemap.download]]
    sha256 = "e146c4a0ceacbc5b10afa6f18a7b28acdf9d395f082682a415e5d6f37551ab5f"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6bf9ec267066de3950846be5dc1332c9681dad0"
os = "windows"

    [[TempestRemap.download]]
    sha256 = "c188d5765cfa5a777b56c487e074697e5b0d5068211aea01758c90063f9e0630"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.2.0+0/TempestRemap.v2.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
