[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78f0561d210ce463b641102cc90ffad593c180ca"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "644cae3db5527b5c19fd4309813585809b455847412fdd5261119a0e1dcdf9a3"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+1/TempestRemap.v2.1.3.aarch64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1d05eaa3069b4748b3d131b33751145656391c1"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "e6e7a4664b0eb864551bf95150bbf7f23000e0fad2ace79f041da1a8cfd5ff4d"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+1/TempestRemap.v2.1.3.aarch64-linux-gnu-cxx11.tar.gz"
[[TempestRemap]]
arch = "x86_64"
git-tree-sha1 = "243b2dd8fc40ea83324cc69d33b9957d4752e757"
os = "macos"

    [[TempestRemap.download]]
    sha256 = "da60a1d87bf23a4e4a106d482d98fedaa0f8dc6e3da198f6fa1475cbb901e8ec"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+1/TempestRemap.v2.1.3.x86_64-apple-darwin.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb950d40682ecbf69a5feb3351275935a1cce72c"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "d65a3ae68fbef9a8b1552cdcb126b870e26cac67a95af69d9e4ee9c45f809e5c"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+1/TempestRemap.v2.1.3.x86_64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e89bd9f52d9a06cdde0165f63e711dd1a9e2343"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "551f8781da4c0230131bbb2b416a00745b0df7da59b9c0668ab519d52e4e2aea"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.3+1/TempestRemap.v2.1.3.x86_64-linux-gnu-cxx11.tar.gz"
