[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d254672bc3c5e90389cdd309f8273a37a7eca9e3"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "58fda365902a2dd9511246ff846797e42e7fff5613969b9be7b7d506c7c600de"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.2+1/TempestRemap.v2.1.2.aarch64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b4b0fc317a3df874dde67117a80e84340ff083c"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "c8b38d4b5e7d9b360c203487aed172f77b95d5badbfce309cf48f79bf86cefc5"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.2+1/TempestRemap.v2.1.2.aarch64-linux-gnu-cxx11.tar.gz"
[[TempestRemap]]
arch = "x86_64"
git-tree-sha1 = "85e91d59799e8cc9bd7b4bcf8f86ab28a1e25147"
os = "macos"

    [[TempestRemap.download]]
    sha256 = "69d1410e63dfd8f8096a5033f394fa73ae305fc7df896d3e1b994072ab603993"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.2+1/TempestRemap.v2.1.2.x86_64-apple-darwin.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "523dc7762659822d94c02729b2a2618d819e653f"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "b15d80f4eeafdbf0baa0de34d6ca8b23811c8e9c9e3c4dff042abc47025d0c31"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.2+1/TempestRemap.v2.1.2.x86_64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12149443dcd9ed8417a3c579c9df728adfaea494"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "fb8b010a07084f01dfc97c8fe241e89939d973b20916b7fcd34f9b1731fcbf19"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.2+1/TempestRemap.v2.1.2.x86_64-linux-gnu-cxx11.tar.gz"
