[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6472adafbdb3abf4a88b357b2b15b5dae292010"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "1647ca83c1c13ff2653cae1871ccb7dab32db1ad7b848530474c1f1e15c0bf17"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.2+2/TempestRemap.v2.1.2.aarch64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e2eb4bb027586def9ecb05cd5a0bec2e2144b92"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "431fc2cf0c36d2fea810e34ccb12c12fe29c8296901367c000ee24e287eb7db9"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.2+2/TempestRemap.v2.1.2.aarch64-linux-gnu-cxx11.tar.gz"
[[TempestRemap]]
arch = "x86_64"
git-tree-sha1 = "37f4317ce35b76c8db88b648830899789f066242"
os = "macos"

    [[TempestRemap.download]]
    sha256 = "ab6d14459deae626a96adcdada7bd11ae8b0c7a6a57048f4d60021ffde7afcd5"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.2+2/TempestRemap.v2.1.2.x86_64-apple-darwin.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d94aa6ddd6a993bebba7023ae1038c486fcb7357"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "7ea0c4bbf309e66a9dcfc3f4b9f02cc3dd2cc97391189dc5d65242877eba6d20"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.2+2/TempestRemap.v2.1.2.x86_64-linux-gnu-cxx03.tar.gz"
[[TempestRemap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad2b8be1a90285442ea8e987e78a421baf21ab92"
libc = "glibc"
os = "linux"

    [[TempestRemap.download]]
    sha256 = "387542fae70b79fe36931c88ca7510311b0cb354457acc9bb405ef452a0b1196"
    url = "https://github.com/JuliaBinaryWrappers/TempestRemap_jll.jl/releases/download/TempestRemap-v2.1.2+2/TempestRemap.v2.1.2.x86_64-linux-gnu-cxx11.tar.gz"
